server:
  port: 8080
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.197.130:3307/itaem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true